development:
  adapter: postgresql
  encoding: unicode
  database: pos_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: pos_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432